export const technologyData = {
  title: "Technology",
  subtitle: "Transforming Ideas with Next-Gen Tech",
  description:
    "Our 400+ AI-enabled developers specialize in cutting-edge technologies and platforms. Our comprehensive tech stack covers everything from design to testing, ensuring seamless and efficient development.",
  techStackData1: [
    { name: "React", logo: "/images/react.webp" },
    { name: "Angular", logo: "/images/angular.webp" },
    { name: "Vue.js", logo: "/images/vue-9-1.webp" },
    { name: "Javascript", logo: "/images/javascript-1.webp" },
    { name: "Bootstrap", logo: "/images/bootstrap.webp" },
    { name: "HTML", logo: "/images/html-5.webp" },
    { name: "CSS", logo: "/images/css3.webp" },
    { name: "IOS", logo: "/images/ios-svgrepo-com.webp" },
    { name: "Ember", logo: "/images/ember-logo.webp" },
    { name: "Next", logo: "/images/nextjs-svgrepo-com.webp" },
    { name: "Node Js", logo: "/images/nodejs.webp" },
    { name: ".NET", logo: "/images/dotnet-1.webp" },
    { name: "ROR", logo: "/images/ror-2.webp" },
    { name: "Swift", logo: "/images/swift.webp" },
    { name: "Kotlin", logo: "/images/kotlinlang-icon.webp" },
    { name: "Java", logo: "/images/java.webp" },
    { name: "Go", logo: "/images/Go-Logo_Aqua.webp" },
    { name: "Flutter", logo: "/images/flutter.webp" },
    { name: "Ionic", logo: "/images/ionic.webp" },
    { name: "AWS", logo: "/images/aws.webp" },
    { name: "Azure", logo: "/images/azure.webp" },
    { name: "Google Cloud", logo: "/images/google-cloud.webp" },
    { name: "Docker", logo: "/images/docker.webp" },
    { name: "Jenkins", logo: "/images/jenkins-new.webp" },
    { name: "Ansible", logo: "/images/anisible.webp" },
    { name: "Kubernetes", logo: "/images/kubernets.webp" },
    { name: "Photoshop", logo: "/images/adobe-photoshop-2.webp" },
    { name: "Illustrator", logo: "/images/adobe-illustrator-cc-icon.webp" },
    { name: "Adobe XD", logo: "/images/adobe-xd-2.webp" },
    { name: "Figma", logo: "/images/figma-1.webp" },
    { name: "Selenium", logo: "/images/selenium-2.webp" },
  ],
  techStackData2: [
    { name: "Kotlin", logo: "/images/kotlinlang-icon.webp" },
    { name: "Flutter", logo: "/images/flutter.webp" },
    { name: "Ionic", logo: "/images/ionic.webp" },
    { name: "Cordova", logo: "/images/cordova-seeklogo.webp" },
    { name: "MongoDB", logo: "/images/mongodb-svgrepo.webp" },
    { name: "Kubernetes", logo: "/images/kubernets.webp" },
    { name: "Photoshop", logo: "/images/adobe-photoshop-2.webp" },
    { name: "Illustrator", logo: "/images/adobe-illustrator-cc-icon.webp" },
    { name: "Adobe XD", logo: "/images/adobe-xd-2.webp" },
    { name: "Figma", logo: "/images/figma-1.webp" },
    { name: "Selenium", logo: "/images/selenium-2.webp" },
    { name: "Python", logo: "/images/python.webp" },
    { name: "PHP", logo: "/images/PHP-logo-1.webp" },
    { name: "Java", logo: "/images/java.webp" },
    { name: "Node Js", logo: "/images/nodejs.webp" },
    { name: "Swift", logo: "/images/swift.webp" },
    { name: "SQL Server", logo: "/images/microsoft-sql-server.webp" },
    { name: "AWS", logo: "/images/aws.webp" },
    { name: "Azure", logo: "/images/azure.webp" },
    { name: "Google Cloud", logo: "/images/google-cloud.webp" },
    { name: "Docker", logo: "/images/docker.webp" },
    { name: "Jenkins", logo: "/images/jenkins-new.webp" },
    { name: "Ansible", logo: "/images/anisible.webp" },
    { name: "React", logo: "/images/react.webp" },
    { name: "Vue.js", logo: "/images/vue-9-1.webp" },
    { name: "Angular", logo: "/images/angular.webp" },
    { name: "Bootstrap", logo: "/images/bootstrap.webp" },
    { name: "HTML", logo: "/images/html-5.webp" },
    { name: "CSS", logo: "/images/css3.webp" },
    { name: ".NET", logo: "/images/dotnet-1.webp" },
    { name: "ROR", logo: "/images/ror-2.webp" },
  ],
  techStackData3: [
    { name: "HTML", logo: "/images/html-5.webp" },
    { name: "CSS", logo: "/images/css3.webp" },
    { name: "Ionic", logo: "/images/ionic.webp" },
    { name: "AWS", logo: "/images/aws.webp" },
    { name: "Azure", logo: "/images/azure.webp" },
    { name: "Google Cloud", logo: "/images/google-cloud.webp" },
    { name: "Docker", logo: "/images/docker.webp" },
    { name: "Selenium", logo: "/images/selenium-2.webp" },
    { name: "Flutter", logo: "/images/flutter.webp" },
    { name: "Xamarin", logo: "/images/xamarin-seeklogo.webp" },
    { name: "Jenkins", logo: "/images/jenkins-new.webp" },
    { name: "Ansible", logo: "/images/anisible.webp" },
    { name: "Photoshop", logo: "/images/adobe-photoshop-2.webp" },
    { name: "Illustrator", logo: "/images/adobe-illustrator-cc-icon.webp" },
    { name: "Javascript", logo: "/images/javascript-1.webp" },
    { name: "Angular", logo: "/images/angular.webp" },
    { name: "Bootstrap", logo: "/images/bootstrap.webp" },

    { name: "React", logo: "/images/react.webp" },
    { name: "Vue.js", logo: "/images/vue-9-1.webp" },
    { name: "Node Js", logo: "/images/nodejs.webp" },
    { name: ".NET", logo: "/images/dotnet-1.webp" },
    { name: "Adobe XD", logo: "/images/adobe-xd-2.webp" },
    { name: "Figma", logo: "/images/figma-1.webp" },
    { name: "Swift", logo: "/images/swift.webp" },
    { name: "Java", logo: "/images/java.webp" },
    { name: "Python", logo: "/images/python.webp" },
    { name: "PHP", logo: "/images/PHP-logo-1.webp" },
    { name: "Kotlin", logo: "/images/kotlinlang-icon.webp" },
    { name: "ROR", logo: "/images/ror-2.webp" },
  ],
};
