import {
  SupportIcon,
  HrChennaiIcon,
  HrBangaloreIcon,
} from "@/public/icons/contactCardImage";

export const headerData = {
  logo: "/images/softsuave_logo.webp",
  logoAlt: "Soft Suave Logo",
  mail: "contact@softsuave.com",
  href: "mailto:contact@softsuave.com",
  contactButtonName: "Let's Connect"
};

export const industriesData = [
  {
    name: "Aviation",
    description: "Enhancing Aviation with Tech",
    href: "/ai-in-aviation",
    icon: "/images/menu-1-1.webp",
    colorClass: "bg-[#fff3ee]",
    hoverColorClass: "hover:bg-[#fff3ee]",
  },
  {
    name: "Edu Tech",
    description: "Transforming Education",
    href: "/ai-solutions-in-edutech",
    icon: "/images/menu-1-2.webp",
    colorClass: "bg-[#eefff4]",
    hoverColorClass: "hover:bg-[#eefff4]",
  },
  {
    name: "Fin Tech",
    description: "Shaping Financial Futures",
    href: "/fintech-ai-solutions",
    icon: "/images/menu-1-3.webp",
    colorClass: "bg-[#f5edff]",
    hoverColorClass: "hover:bg-[#f5edff]",
  },
  {
    name: "Construction",
    description: "Building Tomorrow's World",
    href: "/ai-solutions-for-construction",
    icon: "/images/menu-1-4.webp",
    colorClass: "bg-[#e9f1ff]",
    hoverColorClass: "hover:bg-[#e9f1ff]",
  },
  {
    name: "Health Tech",
    description: "Optimizing Health Solutions",
    href: "/ai-solutions-in-healthtech",
    icon: "/images/menu-1-5.webp",
    colorClass: "bg-[#fff0f0]",
    hoverColorClass: "hover:bg-[#fff0f0]",
  },
  {
    name: "eCommerce",
    description: "Boosting Online Sales",
    href: "/ai-solutions-for-ecommerce",
    icon: "/images/menu-1-6.webp",
    colorClass: "bg-[#ebfffd]",
    hoverColorClass: "hover:bg-[#ebfffd]",
  },
  {
    name: "Logistics",
    description: "Streamlining Supply Chains",
    href: "/ai-in-logistics",
    icon: "/images/menu-1-7.webp",
    colorClass: "bg-[#fff9e8]",
    hoverColorClass: "hover:bg-[#fff9e8]",
  },
  {
    name: "Telecom",
    description: "Connecting Global Networks",
    href: "/ai-solutions-for-telecom",
    icon: "/images/menu-1-8.webp",
    colorClass: "bg-[#f1feff]",
    hoverColorClass: "hover:bg-[#f1feff]",
  },
];

export const servicesData = [
  {
    id: "team-expertise",
    name: "By Team Expertise",
    icon: "/images/service-mega-1.webp",
    description: "",
    href: "",
    colorClass: "",
    hoverColorClass: "",
    services: [
      {
        id: "global-capability",
        name: "Global Capability Center",
        description: "Empowering Global Teams",
        icon: "/images/team-expertice-3.webp",
        href: "/global-capability-center",
        color: "bg-[#fff3ee]",
        hoverColorClass: "hover:bg-[#fff3ee]",
      },
      {
        id: "ai-solutions",
        name: "AI Solutions",
        description: "AI that Drives Progress",
        icon: "/images/team-expertice-5.webp",
        href: "/ai-development-service",
        color: "bg-[#eefff4]",
        hoverColorClass: "hover:bg-[#eefff4]",
      },
      {
        id: "offshore-development",
        name: "Offshore Development",
        description: "Cost-Effective Solutions",
        icon: "/images/team-expertice-6.webp",
        href: "/offshore-software-development-company",
        color: "bg-[#f5edff]",
        hoverColorClass: "hover:bg-[#f5edff]",
      },
      {
        id: "it-staff-augmentation",
        name: "IT Staff Augmentation",
        description: "Scale Your Tech Team",
        icon: "/images/team-expertice-1.webp",
        href: "/it-staff-augmentation-services",
        color: "bg-[#e9f1ff]",
        hoverColorClass: "hover:bg-[#e9f1ff]",
      },
      {
        id: "on-demand-teams",
        name: "On-demand Teams",
        description: "Flexible Talent Access",
        icon: "/images/team-expertice-2.webp",
        href: "/hire-dedicated-developers",
        color: "bg-[#fff9e8]",
        hoverColorClass: "hover:bg-[#fff9e8]",
      },
      {
        id: "legacy-modernization",
        name: "Legacy Modernization",
        description: "Modernizing Old Systems",
        icon: "/images/team-expertice-4.webp",
        href: "/legacy-modernization-developers",
        color: "bg-[#f1feff]",
        hoverColorClass: "hover:bg-[#f1feff]",
      },
    ],
  },
  {
    id: "mobile-development",
    name: "Mobile App Development",
    icon: "/images/service-mega-2.webp",
    description: "",
    href: "",
    colorClass: "",
    hoverColorClass: "",
    services: [
      {
        id: "mobile-main",
        name: "Mobile App Development",
        description: "Shaping Financial Futures",
        icon: "/images/services-icon-1.png",
        href: "/mobile-application-development-company",
        color: "bg-[#FFEFF3]",
        hoverColorClass: "hover:bg-[#FFEFF3]",
      },
      {
        id: "android",
        name: "Android",
        description: "",
        icon: "/images/header-mob-1.webp",
        href: "/android-application-development-company",
        color: "bg-[#F6FFED]",
        hoverColorClass: "hover:bg-[#F6FFED]",
      },
      {
        id: "ios",
        name: "iOS",
        description: "",
        icon: "/images/header-mob-2.webp",
        href: "/ios-application-development-company",
        color: "bg-[#EEEEEE]",
        hoverColorClass: "hover:bg-[#EEEEEE]",
      },
      {
        id: "react-native",
        name: "React Native",
        description: "",
        icon: "/images/header-mob-3.webp",
        href: "/hire-react-native-developers",
        color: "bg-[#E7FAFF]",
        hoverColorClass: "hover:bg-[#E7FAFF]",
      },
      {
        id: "flutter",
        name: "Flutter",
        description: "",
        icon: "/images/header-mob-4.webp",
        href: "/flutter-application-development-company",
        color: "bg-[#E7FAFF]",
        hoverColorClass: "hover:bg-[#E7FAFF]",
      },
      {
        id: "ionic",
        name: "Ionic",
        description: "",
        icon: "/images/header-mob-5.webp",
        href: "/ionic-app-development-company",
        color: "bg-[#DFF4FF]",
        hoverColorClass: "hover:bg-[#DFF4FF]",
      },
      {
        id: "xamarin",
        name: "Xamarin",
        description: "",
        icon: "/images/header-mob-6.webp",
        href: "/xamarin-app-development-company",
        color: "bg-[#DFF4FF]",
        hoverColorClass: "hover:bg-[#DFF4FF]",
      },
    ],
  },
  {
    id: "web-development",
    name: "Web App Development",
    description: "",
    icon: "/images/service-mega-3.webp",
    href: "",
    colorClass: "",
    hoverColorClass: "",
    services: [
      {
        id: "web-main",
        name: "Web App Development",
        description: "Shaping Financial Futures",
        icon: "/images/services-icon-2.png",
        href: "/web-application-development-company",
        color: "bg-[#FFEFF3]",
        hoverColorClass: "hover:bg-[#FFEFF3]",
      },
      {
        id: "react",
        name: "React",
        description: "",
        icon: "/images/header-web-1.webp",
        href: "/reactjs-application-development-company",
        color: "bg-[#E7FAFF]",
        hoverColorClass: "hover:bg-[#E7FAFF]",
      },
      {
        id: "angular",
        name: "Angular",
        description: "",
        icon: "/images/header-web-2.webp",
        href: "/angularjs-application-development-company",
        color: "bg-[#FFF2EF]",
        hoverColorClass: "hover:bg-[#FFF2EF]",
      },
      {
        id: "ror",
        name: "ROR",
        description: "",
        icon: "/images/header-web-4.webp",
        href: "/ruby-on-rails-application-development-company",
        color: "bg-[#FFEDED]",
        hoverColorClass: "hover:bg-[#FFEDED]",
      },
      {
        id: "nodejs",
        name: "Node.js",
        description: "",
        icon: "/images/header-web-5.webp",
        href: "/nodejs-application-development-company",
        color: "bg-[#EFFFF7]",
        hoverColorClass: "hover:bg-[#EFFFF7]",
      },
      {
        id: "java",
        name: "Java",
        description: "",
        icon: "/images/header-web-6.webp",
        href: "/java-application-development-company",
        color: "bg-[#E7F2FE]",
        hoverColorClass: "hover:bg-[#E7F2FE]",
      },
      {
        id: "python",
        name: "Python",
        description: "",
        icon: "/images/header-web-7.webp",
        href: "/python-application-development-company",
        color: "bg-[#E7F2FE]",
        hoverColorClass: "hover:bg-[#E7F2FE]",
      },
      {
        id: "php",
        name: "PHP",
        description: "",
        icon: "/images/header-web-8.webp",
        href: "/php-application-development-company",
        color: "bg-[#F2F4FF]",
        hoverColorClass: "hover:bg-[#F2F4FF]",
      },
      {
        id: "dotnet",
        name: ".Net",
        description: "",
        icon: "/images/header-web-9.webp",
        href: "/dot-net-application-development-company",
        color: "bg-[#ede9fa]",
        hoverColorClass: "hover:bg-[#ede9fa]",
      },
    ],
  },
  {
    id: "others",
    name: "Others",
    description: "",
    icon: "/images/service-mega-4.webp",
    href: "",
    colorClass: "",
    hoverColorClass: "",
    services: [
      {
        id: "it-outsourcing",
        name: "IT Outsourcing Service",
        description: "Efficient IT Solutions",
        icon: "/images/header-other-4.webp",
        href: "/it-outsourcing-company-india",
        color: "bg-[#f1feff]",
        hoverColorClass: "hover:bg-[#f1feff]",
      },
      {
        id: "product-engineering",
        name: "Product Engineering",
        description: "Innovating Your Products",
        icon: "/images/header-other-2.webp",
        href: "/product-engineering-services",
        color: "bg-[#fff9e8]",
        hoverColorClass: "hover:bg-[#fff9e8]",
      },
      {
        id: "cloud-computing",
        name: "Cloud Computing",
        description: "Scalable Cloud Services",
        icon: "/images/header-other-1.webp",
        href: "/cloud-computing",
        color: "bg-[#e9f1ff]",
        hoverColorClass: "hover:bg-[#e9f1ff]",
      },
    ],
  },
];
export const companyData = [
  {
    name: "About Us",
    description: "Know Our Story & Vision",
    href: "/about",
    icon: "/images/menu-2-1.webp",
    colorClass: "bg-[#fff3ee]",
    hoverColorClass: "hover:bg-[#fff3ee]",
  },
  {
    name: "Awards",
    description: "Recognized for Excellence",
    href: "/awards-recognition",
    icon: "/images/menu-2-2.webp",
    colorClass: "bg-[#eefff4]",
    hoverColorClass: "hover:bg-[#eefff4]",
  },
  {
    name: "Clients",
    description: "Trusted by Leading Brands",
    href: "/clients",
    icon: "/images/menu-2-3.webp",
    colorClass: "bg-[#f5edff]",
    hoverColorClass: "hover:bg-[#f5edff]",
  },
  {
    name: "Success Stories",
    description: "Real Client Wins, Real Impact",
    href: "/success-stories",
    icon: "/images/menu-2-4.webp",
    colorClass: "bg-[#e9f1ff]",
    hoverColorClass: "hover:bg-[#e9f1ff]",
  },
  {
    name: "Contact Us",
    description: "Let's Start a Conversation",
    href: "/contact",
    icon: "/images/menu-2-5.webp",
    colorClass: "bg-[#fff0f0]",
    hoverColorClass: "hover:bg-[#fff0f0]",
  },
  {
    name: "Life st Soft Suave",
    description: "Discover Our Work Culture",
    href: "/life-at-softsuave",
    icon: "/images/menu-2-6.webp",
    colorClass: "bg-[#ebfffd]",
    hoverColorClass: "hover:bg-[#ebfffd]",
  },
  {
    name: "Career",
    description: "Join Our Growing Team",
    href: "/career-overview",
    icon: "/images/menu-2-7.webp",
    colorClass: "bg-[#fff9e8]",
    hoverColorClass: "hover:bg-[#fff9e8]",
  },
];

export const resourcesData = [
  {
    name: "Blog",
    description: "Insights, Trends & Tips",
    href: "/blog",
    icon: "/images/menu-4-1.webp",
    colorClass: "bg-[#fff3ee]",
    hoverColorClass: "hover:bg-[#fff3ee]",
  },
  {
    name: "Case Study",
    description: "Our Solutions in Action",
    href: "/case-studies",
    icon: "/images/menu-4-2.webp",
    colorClass: "bg-[#eefff4]",
    hoverColorClass: "hover:bg-[#eefff4]",
  },
];

export const contactCardData = {
  title: "Soft Suave Contacts",
  contactSection: [
    {
      title: "For Business Inquiry",
      img: SupportIcon,
      text: "",
      lists: [
        {
          country: "USA",
          text: "+1 (410) 220-6301",
          icon: "/images/USA-Flag.webp",
          href: "tel:+14102206301",
          extras: false,
        },
        {
          country: "UK",
          text: "+44 7403 646450",
          icon: "/images/uk-flag.png",
          href: "tel:+447403646450",
          extras: false,
        },
        {
          country: "India",
          text: "+91 99527 32708",
          icon: "/images/IND-Flag.webp",
          href: "tel:+919952732708",
          extras: true,
        },
        {
          country: "mail",
          text: "contact@softsuave.com",
          icon: "",
          href: "mailto:contact@softsuave.com",
          extras: false,
        },
      ],
      redirectText: "If we don’t pick up,",
      redirectTextLink: "drop inquiry.",
      redirectLink: "/contact",
    },
    {
      title: "For HR Inquiry(Jobs)",
      img: HrChennaiIcon,
      text: "Chennai -",
      lists: [
        {
          country: "Chennai",
          text: "+91 8015159981",
          icon: "",
          href: "tel:8015159981",
          extras: true,
        },
        {
          country: "mail",
          text: "careers@softsuave.com",
          icon: "",
          href: "mailto:careers@softsuave.com",
          extras: false,
        },
      ],
      redirectText: "If we don’t pick up,",
      redirectTextLink: "drop inquiry.",
      redirectLink: "/contact",
    },
    {
      title: "",
      img: HrBangaloreIcon,
      text: "Bangalore -",
      lists: [
        {
          country: "Bangalore",
          text: "080 4216 1324",
          icon: "",
          href: "tel:08042161324",
          extras: true,
        },
        {
          country: "mail",
          text: "teamhr.bangalore@softsuave.com",
          icon: "",
          href: "mailto:teamhr.bangalore@softsuave.com",
          extras: false,
        },
      ],
      redirectText: "If we don’t pick up,",
      redirectTextLink: "drop inquiry.",
      redirectLink: "/contact",
    },
  ],
  whatsappImage: "/images/Whatsapp.webp",
  whatsappImageAlt: "WhatsApp",
};

export const tabData = [
  {
    tabName: "isIndustries",
    headerName: "Industries",
    headerDesc:
      "Explore the diverse industries we serve with innovative, tech-driven solutions.",
    headerImage: "/images/industries-header-img.webp",
    headerStore: industriesData,
    headerButton: "See all Industries",
  },
  {
    tabName: "isServices",
    headerName: "Services",
    headerDesc:
      "Discover our range of services designed to drive business transformation.",
    headerImage: "/images/header-servce-image.webp",
    headerStore: servicesData,
    headerButton: "",
  },
  {
    tabName: "isCompany",
    headerName: "Company",
    headerDesc:
      "Learn more about our vision, values, and the team behind our success.",
    headerImage: "/images/header-company-image.webp",
    headerStore: companyData,
    headerButton: "",
  },
  {
    tabName: "isResources",
    headerName: "Resources",
    headerDesc: "Access valuable resources to stay informed and inspired",
    headerImage: "/images/industries-header-img.webp",
    headerStore: resourcesData,
    headerButton: "",
  },
];
